added RAGAS metrics
mindsdb/mindsdb_evaluator pull request #41
Opened 2024-08-02 17:09 UTC by abhayasr

2024-08-05 18:07 UTC, paxcema requested changes
Very good start :+1: Once the points I've raised are addressed, I think this would be good to merge (at which point, we can also do a release & check the related `mindsdb` PR against the new package version).

2024-08-05 18:07 UTC, paxcema commented on mindsdb_evaluator/accuracy/llm_generation.py
> +    faithfulness_score = evaluate(dataset, metrics=[faithfulness, context_recall, context_precision, answer_relevancy])
This computes all `ragas` scores at once. That makes sense, but to follow the pattern we use in other domain's evals (for package consistency), we should turn this into a lower level method `evaluate_rag` that would compute just the metrics the user asks for. It would re-use 99% of this code as-is, just modifying the actual `metrics` argument that goes into `ragas.evaluate` depending on user input. Something like this:


```python
def evaluate_rag(..., metric: str) -> pd.DataFrame:
    ....
    score = evaluate(dataset, metrics=[metric])  # notice it is now a single metric, instead of all of them
```

And then in `accuracy/general`, we do the dispatch:

```python

if accuracy_function == `rag_faithfulness`:
    ...
    score = evaluate_rag(answer, context, question, ground_truth, metric='faithfulness')  # we pass the RAGAS metric name here
elif accuracy_function == 'rag_context_recall':
    ...
    score = evaluate_rag(answer, context, question, ground_truth, metric='context_recall')  # we pass the RAGAS metric name here

# ...etc
```

2024-08-05 18:07 UTC, paxcema commented on mindsdb_evaluator/accuracy/general.py
> +from mindsdb_evaluator.accuracy.llm_generation import evaluate_faithfulness
See comment about restructuring code. It means we'd change this to one import per RAGAS metric here.

2024-08-05 18:07 UTC, paxcema commented on mindsdb_evaluator/accuracy/general.py
> +        print(data)
Let's remove prints once the PR is out of draft

2024-08-05 18:07 UTC, paxcema commented on mindsdb_evaluator/accuracy/general.py
> +                                        [str(y) for y in y_pred],
The removed whitespace here is probably unintentional, please restore to old state (otherwise lint check will fail)

2024-08-07 20:36 UTC, paxcema requested changes

2024-08-07 20:36 UTC, paxcema commented on pyproject.toml
> +pytest = "^8.3.2"
Do we need `pytest`? Looking at our tests, we're only using `unittest` so we can remove this

2024-08-07 20:36 UTC, paxcema commented on mindsdb_evaluator/accuracy/general.py
> +def is_llm(metric: str) -> bool:
Let's move this method to `mindsdb_evaluator.helpers.general`

2024-08-07 20:36 UTC, paxcema commented on mindsdb_evaluator/accuracy/general.py
> +    def rag_eval(data: pd.DataFrame) -> dict:
I'd rather we keep everything specific to LLM/RAG away from this `general` dispatch method, and to avoid nested functions if possible. For that, let's move this method to `llm_generation.py`. After checking its usage, I would also recommend the following refactoring as a nice to have: 

1. Change name from `rag_eval` to `_setup_rag_eval` or similar (note: the leading `_` means this method should not be used outside of `llm_generation.py`, but it is just a naming convention and not actually checked by the runtime. 
2. Following your implementation, once the `if is_llm` conditional is triggered, we don't need to maintain the signature for the `evaluate_rag` accuracy function similar to others, so I recommend to change it to `evaluate_rag(metric: str, fields: dict)` for simplicity, and then parse the fields internally:

```python
# in evaluate_accuracy()
fields = _setup_rag_eval(data)
metric = accuracy_function.replace('rag_', '')
score = evaluate_rag(metric, fields)
```

```python
# inside evaluate_rag()
try:
    data = {
        "question": fields['question'],
        "contexts": fields['new_context'],
        "answer": fields['predictions'],
        "ground_truth": fields['ground_truth'],
    }
except KeyError:
    raise Exception(f'To evaluate `{metric}`, check that your input data contains `question`, `context`, `ground_truth` and try again')
```

2024-08-07 20:36 UTC, paxcema commented on mindsdb_evaluator/accuracy/llm_generation.py
> +    result = [score for score in ragas_score[metric] if not np.isnan(score)]
Open question: if a `score` is `nan`, shouldn't we consider it somehow for the average? Perhaps depending on exactly which metric has been computed. 

I think this is fine for now, but perhaps let's leave a comment here about considering this further.

2024-08-07 20:49 UTC, abhayasr commented on pyproject.toml
> +pytest = "^8.3.2"
i added this by accident how do I remove it

2024-08-07 21:25 UTC, abhayasr commented on mindsdb_evaluator/accuracy/llm_generation.py
> +    result = [score for score in ragas_score[metric] if not np.isnan(score)]
Yeah i agree i just didn't know how to deal with it because it was throwing an error

2024-08-09 15:06 UTC, paxcema approved these changes
Nice work :raised_hands: !

2024-08-09 15:07 UTC, merged